

from posixpath import basename
from django.urls import path
from .views import *
from pharm import views

urlpatterns = [
    path('api/get_all_sources/', views.getAllSources),
    path('api/get_destinations/', views.getAllDestinations),
    path('api/get_selected_sources/<int:id>', views.getSelectedSources),
    path('api/create_new_source/', views.createNewSource),
    path('api/update_source/<int:id>', views.updateSource),
    path('api/delete_source/<int:id>', views.deleteSource),
    path('api/get_all_medicaments/', views.getAllMedicaments),
    path('api/get_all_medicaments_names/', views.getAllMedicamentsNames),
    path('api/get_selected_medicament/<int:id>', views.getSelectedMedicament),
    path('api/add_medicament/', views.addMedicament),
    path('api/update_medicament/<int:id>', views.updateMedicament),
    path('api/delete_medicament/<int:id>', views.deleteMedicament),
    path('api/get_all_stocks/', views.getAllStocks),
    path('api/get_all_stocks_expired/', views.getAllStocksExpired),
    path('api/get_all_stocks_expired_alredy/', views.getAllStocksExpiredAlredy),
    path('api/get_all_stocks_expired_notyet/', views.getAllStocksExpiredNotYet),
    path('api/get_all_arivage_of_medic/<int:id>', views.getAllArivageOfMedic),
    path('api/get_selected_stock/<int:id>', views.getSelectedStock),
    path('api/add_stock/', views.addStock),
    path('api/add_stock_to_arrivage/', views.addStockToArivage),
    path('api/update_stock/<int:id>', views.updateStock),
    path('api/delete_stock/<int:id>', views.deleteStock),
    path('api/get_all_bon_sortie/<int:month>/<int:year>', views.getAllBonSorties),
    path('api/get_first_bon_sortie/', views.getFirstBonSortieItems),
    path('api/get_selected_bon_sortie/<int:id>', views.getSelectedBonSortie),
    path('api/check_bon_sortie_id/<int:id>', views.checkBonSortieId),
    path('api/add_bon_sortie/', views.addBonSortie),
    path('api/update_bon_sortie/<int:id>', views.updateBonSortie),
    path('api/delete_bon_sortie/<int:id>', views.deleteBonSortie),
    path('api/get_all_bon_sortie_items/<int:month>/<int:year>', views.getAllBonSortieItems),
    path('api/get_selected_bon_sortie_item/<int:id>', views.getSelectedBonSortieItem),
    path('api/add_bon_sortie_item/', views.addBonSortieItem),
    path('api/update_bon_sortie_item/<int:id>', views.updateBonSortieItem),
    path('api/delete_bon_sortie_item/<int:id>', views.deleteBonSortieItem),
    path('api/get_all_fournisseurs/', views.getAllFournisseurs),
    path('api/get_selected_fournisseur/<int:id>', views.getSelectedFournisseur),
    path('api/add_fournisseurs/', views.createNewFournisseur),
    path('api/update_fournisseurs/<int:id>', views.updateFournisseur),
    path('api/delete_fournisseurs/<int:id>', views.deleteFournisseur),
    path('api/get_all_bon_commande/', views.getAllBonCommande),
    path('api/add_bon_commande/', views.addBonCommande),
    path('api/update_bon_commande/', views.updateBonCommande),
    path('api/delete_bon_commande/', views.deleteBonCommande),
    path('api/add_bon_commande_item/', views.addBonCommandeItem),
    path('api/update_bon_commande_item/', views.updateBonCommandeItem),
    path('api/delete_bon_commande_item/', views.deleteBonCommandeItem),
    path('api/get_all_arivage/', views.getAllArivage),
    path('api/add_arivage/', views.addArivage),
    path('api/update_arivage/', views.updateArivage),
    path('api/delete_arivage/', views.deleteArivage),
    path('api/add_arivage_item/', views.addArivageItem),
    path('api/update_arivage_item/', views.updateArivageItem),
    path('api/delete_arivage_item/', views.deleteArivageItem),
    path('api/get_cost_by_service/<int:month>/<int:year>', views.getCostByService),

    path('api/get_all_bon_arrivage/<int:month>/<int:year>', views.getAllBonArrivage),
    path('api/get_selected_bon_arrivage/<int:id>', views.getSelectedBonArrivage),
    path('api/check_bon_arrivage_id/<int:id>', views.checkBonArrivageId),
    path('api/add_bon_arrivage/', views.addBonArrivage),
    path('api/update_bon_arrivage/<int:id>', views.updateBonArrivage),
    path('api/delete_bon_arrivage/<int:id>', views.deleteBonArrivage),
    path('api/get_all_bon_arrivage_items/<int:month>/<int:year>', views.getAllBonArrivageItems),
    path('api/get_selected_bon_arrivage_item/<int:id>', views.getSelectedBonArrivageItem),
    path('api/add_bon_arrivage_item/', views.addBonArrivageItem),
    path('api/add_bon_arrivage_item_cust/', views.addBonArrivageItemCustom),
    path('api/update_bon_arrivage_item/<int:id>', views.updateBonArrivageItem),
    path('api/delete_bon_arrivage_item/<int:id>', views.deleteBonArrivageItem),
    path('api/get_fourn_for_selection/', views.getAllFournForSelection),

    path('api/get_all_articles/', views.getAllArticles),
    path('api/get_all_articles_names/', views.getAllArticlesNames),
    path('api/get_selected_article/<int:id>', views.getSelectedArticle),
    path('api/add_article/', views.addArticle),
    path('api/update_article/<int:id>', views.updateArticle),
    path('api/delete_article/<int:id>', views.deleteArticle),

    
    path('api/generate_qnt_conv_by_year/<int:year>', views.generateQntConvByYear),
    path('api/get_all_qnt_conv_by_year/<int:year>', views.getAllQntConvByYear),
    path('api/delete_qnt_conv_by_year/<int:year>', views.deleteQntConvByYear),
    path('api/save_qnt_conv_by_year/', views.saveStateQntConv),

    path('api/generate_consomation_by_year/<int:month>/<int:year>', views.generateConsomationByYearByMonth),
    path('api/get_all_consomation_year/<int:month>/<int:year>', views.getAllConsomationByYearByMonth),
    path('api/delete_consomation/<int:month>/<int:year>', views.deleteConsomationByYearByMonth),
]